src/views/DeviceInspector/OverviewTab.js

Since we 0-index like weirdos, so this should be 40 minutes.

fix: We actually do 4 reboots

---

Makefile

This adds a target to the Makefile for testing. Currently our tests are "did it build?"

stub out testing for buildbot

---

src/views/DeviceInspector/OverviewTab.js

We are doing burn-in ourselves on KR expansion. Run a rack for 6hr.

Bump burnin from 40m to 6hr for KRx1

---

Makefile
src/__mocks__/mithril.js
src/__mocks__/mithril/request.js
src/util/Request.js
src/util/Request.test.js

This fixes the test mocks for the Request layer (by mocking `m.request`) and allows us to test in an environment without a database.

Better mocks

---

src/dispatch.js
src/models/Device.js
src/models/HardwareProduct.js
src/models/Rack.js
src/models/User.js
src/models/ValidationPlan.js
src/models/Validations.js
src/models/Workspace.js
src/views/DatacenterBrowser/EditLayoutModal.js
src/views/DatacenterBrowser/index.js
src/views/DeviceInspector/ValidationTab.js
src/views/DeviceInspector/index.js
src/views/Devices/index.js
src/views/Status/index.js

#43 wants us to purge the Workspace Validations UI so we can purge the underlying endpoint and the crazy that makes it work.
This PR does that and brings in a bunch of the underlying model changes we've been working on as well.

Purge Workspace Validations UI

---

src/models/Workspace.js

Clear the stale token to prevent infinite loop

---

src/views/DeviceInspector/OverviewTab.js
src/views/Status/index.js
src/views/component/DeviceStatus.js

Closes https://github.com/joyent/conch-ui/issues/85
Conch GHI: https://github.com/joyent/conch/issues/447
Conch PR: https://github.com/joyent/conch/pull/703
**Note:** I'll be making these changes to the Vue port as well because I need them for the unit tests to pass.

Device health values are now always lower-cased

---

src/styles/main.scss
src/views/User/UserProfile.vue
src/views/User/__tests__/UserProfile.test.js
src/views/User/__tests__/__snapshots__/UserProfile.test.js.snap

- Adds password confirmation input field
- Adds specific warnings if password or password confirmation don't meet requirements
- Adds some visual helpers to show when requirements are met
Closes https://github.com/joyent/conch-ui/issues/37.

Improves password reset workflow

---

src/api/users.js
src/styles/main.scss
src/styles/partials/_toggle-switch.scss
src/views/User/UserActionModal.vue
src/views/User/UserAuthTokens.vue
src/views/User/UserProfile.vue
src/views/User/__tests__/UserActionModal.test.js
src/views/User/__tests__/__snapshots__/UserProfile.test.js.snap

Add options to clear tokens during password reset and user deactivation flows

---

src/views/Sidebar/Sidebar.vue
src/views/Sidebar/__tests__/Sidebar.test.js

- Adds a loading indicator until required data is available.
- Resolves warnings in the browser dev tools console

Small fix for Sidebar

---

src/__fixtures__/deviceDetails.js
src/__fixtures__/rackLayout.js
src/api/__tests__/device.test.js
src/api/__tests__/rack.test.js
src/api/__tests__/users.test.js
src/api/device.js
src/api/rack.js
src/api/users.js
src/store/__tests__/getters.test.js
src/store/getters.js
src/styles/main.scss
src/views/DataCenterBrowser/LayoutPanel.vue
src/views/DataCenterBrowser/RackPanel.vue
src/views/DataCenterBrowser/__tests__/LayoutPanel.test.js
src/views/DataCenterBrowser/__tests__/RackPanel.test.js
src/views/DeviceInspector/OverviewTab.vue
src/views/DeviceInspector/__tests__/OverviewTab.test.js
src/views/components/PhaseUpdateModal.vue
src/views/components/__tests__/PhaseUpdateModal.test.js
webpack.dev.js

Closes https://github.com/joyent/conch-ui/issues/105

Add phases to devices and racks

---

src/styles/main.scss
src/styles/partials/_table.scss
src/views/AuthenticationTokens/AuthenticationTokens.vue
src/views/User/UsersTable.vue
src/views/components/TablePagination.vue
src/views/components/__tests__/TablePagination.test.js

This adds a TablePagination component.
**Uses:**
- Decrease initial page sizes due to the number of results in a table.
- Increase initial page load performance by decreasing the number of results initially loaded into a table
**Goals:**
- I'd eventually like to apply this to pages with heavy initial load times, such as the Device browser, which currently loads over 10,000 devices on a single page during initial render.

Adds TablePagination component and applies it to user list tables

---

src/styles/main.scss
src/views/components/DeviceModal.vue

Closes https://github.com/joyent/conch-ui/issues/121.

Sets min and max heights for device inspector modal

---

config.js.dist
package.json
src/api/__mocks__/conchApiVersion.js
src/styles/main.scss
src/views/SignIn/SignIn.vue
src/views/SignIn/__tests__/SignIn.test.js
yarn.lock

Closes https://github.com/joyent/conch-ui/issues/112.

Adds Conch API version requirements

---

src/api/request.js

Closes https://github.com/joyent/conch-ui/issues/113.
Header format looks like this:
`X-Conch-UI: v2.1.22.3-235-g90962f4`

Include X-Conch-UI with UI version in request headers

---

src/api/__tests__/device.test.js
src/api/__tests__/workspaces.test.js
src/api/device.js
src/api/rack.js
src/api/workspaces.js
src/store/actions.js
src/store/mutations.js
src/store/state.js
src/styles/components/_edit-layout-modal.scss
src/styles/config/_variables.scss
src/styles/main.scss
src/styles/partials/_tooltip.scss
src/views/DataCenterBrowser/EditLayoutModal.vue
src/views/DataCenterBrowser/LayoutPanel.vue
src/views/DataCenterBrowser/__tests__/EditLayoutModal.test.js
src/views/shared/utils.js

A small redesign of how the Edit Layout Modal looks, and large redesign of how it functions underneath:
- Modal now uses the correct API endpoints
- Adds Input validation using generally accepted parameters:
- Serial number must be unique and must not contain a period, forward slash or whitespace
- Asset tag must be unique
- Adds UI messages for successful and unsuccessful changes
Closes https://github.com/joyent/conch-ui/issues/149.

Fix rack assignment issues

---

src/styles/components/_user-management.scss
src/views/UserManagement/UserManagement.vue
src/views/UserManagement/UsersTable.vue
src/views/UserManagement/__tests__/UserManagement.test.js

Improvements:
1. Clearly indicate which filter is active
2. Fix table numbering
Closes https://github.com/joyent/conch-ui/issues/151 and https://github.com/joyent/conch-ui/issues/150

User Management improvements

---

src/api/authentication.js
src/views/SignIn/SignIn.vue
src/views/SignIn/__tests__/SignIn.test.js

- Makes it clearer what information is being passed to the request object
- Adds some documentation for the login function

Update login endpoint to use parameter email instead of user

---

.babelrc
src/styles/components/_edit-layout-modal.scss

a1673ee - Adds a Babel plugin to allow async functions
60897c2 - Makes the modal for editing a rack layout slightly wider to fix a styling issue

Small fixes

---

src/__tests__/App.test.js
src/api/__tests__/device.test.js
src/api/__tests__/hardwareProduct.test.js
src/api/__tests__/rack.test.js
src/api/__tests__/request.test.js
src/api/__tests__/users.test.js
src/api/__tests__/validations.test.js
src/api/__tests__/workspaces.test.js
src/api/request.js
src/store/__tests__/getters.test.js
src/store/getters.js
src/views/DataCenterBrowser/__tests__/DataCenterBrowser.test.js
src/views/Devices/__tests__/Devices.test.js
src/views/Navbar/Navbar.vue
src/views/SignIn/SignIn.vue
src/views/Status/__tests__/Status.test.js
src/views/shared/__tests__/utils.test.js

This will fix the issue of not being able to work on multiple tabs.
Fixes https://github.com/joyent/conch-ui/issues/156

Use localStorage instead of sessionStorage

---

package.json
yarn.lock

Revert "Move @vue/cli-service from devDependencies to dependencies to resolve…"

---

src/App.vue
src/styles/components/_sign-in.scss
src/views/SignIn/SignIn.vue

Closes https://github.com/joyent/conch-ui/issues/177.
Closes https://github.com/joyent/conch-ui/issues/180.

v4 beta fixes

---

src/api/workspaces.js
src/views/UserProfile/AccountSettingsTab.vue

Closes https://github.com/joyent/conch-ui/issues/118.
Closes https://github.com/joyent/conch-ui/issues/162.
Closes https://github.com/joyent/conch-ui/issues/163.

v4 beta fixes and improvements

---

src/api/users.js

without it, the left sidebar sits with an infinite spinner and never
populates.
(resolves #197.)

send token for these authenticated endpoints

---

src/views/Builds/DevicesTab.vue
src/views/Builds/OrganizationsTab.vue
src/views/Builds/RacksTab.vue

Fix display on build page tabs when filtering results

---

src/views/Builds/DevicesTab.vue
src/views/Builds/RacksTab.vue

- also fixes the hardware product column and improves searching

Adds Rack Unit and Last Reported columns to build device table

---

package.json
src/main.js
src/styles/partials/_toast.scss
src/views/SignIn/SignIn.vue
src/views/UserManagement/ResetPassword.vue
yarn.lock

Closes https://github.com/joyent/conch-ui/issues/261.

Adds better error messaging for login page

---

vue.config.js

Closes https://github.com/joyent/conch-ui/issues/287

CSS cache busting

---

src/views/DeviceInspector/ValidationTab.vue

Closes https://github.com/joyent/conch-ui/issues/246
Closes https://github.com/joyent/conch-ui/issues/285

Fixes validations
